In [3]:
import numpy as np

In [4]:
np.array([1, 2, 8, 9])

array([1, 2, 8, 9])

In [5]:
np.zeros(5, dtype=float)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.ones((3,4,3), dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [10]:
np.zeros((2, 2, 3), dtype=float)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(2,15,3)

array([ 2,  5,  8, 11, 14])

In [13]:
np.linspace(0,3,9)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [15]:
np.random.random((2,3))


array([[0.92139123, 0.1284513 , 0.70128576],
       [0.73314306, 0.02405731, 0.87071119]])

In [16]:
np.random.random((3,4,5))

array([[[0.50037048, 0.8312306 , 0.6305969 , 0.31062424, 0.19370941],
        [0.94901185, 0.95474702, 0.27147476, 0.22702995, 0.81332489],
        [0.85441307, 0.03574942, 0.00279799, 0.18622214, 0.19021171],
        [0.130854  , 0.13891721, 0.4975892 , 0.69389132, 0.47207833]],

       [[0.19427396, 0.91490383, 0.10775046, 0.45030083, 0.74463743],
        [0.5894716 , 0.37021483, 0.13922627, 0.93976462, 0.76768769],
        [0.78049946, 0.84137119, 0.55613254, 0.08605389, 0.50098783],
        [0.91372114, 0.80196306, 0.49604022, 0.73849806, 0.43685847]],

       [[0.06110872, 0.18697672, 0.16546589, 0.31041981, 0.60213594],
        [0.57980743, 0.5833772 , 0.47358379, 0.89179989, 0.05516954],
        [0.34481653, 0.04617345, 0.53734014, 0.31815244, 0.7728244 ],
        [0.39626595, 0.57120398, 0.03678368, 0.26584185, 0.42529773]]])

In [19]:
np.random.normal(0, 1, (1, 3))

array([[ 1.6952733 ,  0.60467648, -1.24418171]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [22]:
np.eye(4, 6, 3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [1]:
c=[[77, 65, 66, 92, 85] ,[45, 66, 77, 68, 71]]
x=[]
for i in range(5):
    x.append((c[0][i]+c[1][i])/2)
print(x)

[61.0, 65.5, 71.5, 80.0, 78.0]


In [7]:
t=max(x)
y=[]
for i in range(5):
    y.append((x[i]*100)/t)
print(y)

[76.25, 81.875, 89.375, 100.0, 97.5]


In [ ]:
print(r apple \n mango )